document.addEventListener('DOMContentLoaded',function(){if(window.location.pathname==='/'||window.location.pathname==='/index.html'){initABTest();}});function initABTest(){let variant=localStorage.getItem('hero_variant');if(!variant){variant=Math.random()<0.5?'A':'B';localStorage.setItem('hero_variant',variant);}
if(variant==='B'){applyVariantB();}
trackEvent('hero_view',{variant});}
function applyVariantB(){const heroSection=document.getElementById('hero');if(!heroSection)return;const heroContent=heroSection.querySelector('.hero-content');if(!heroContent)return;const headline=heroContent.querySelector('h1');if(headline){headline.textContent='Transform Your Small Business with AI Solutions';}
const subheadline=heroContent.querySelector('p');if(subheadline){subheadline.textContent='Get started with AI today. Easy to implement, affordable solutions with proven ROI for businesses of any size.';}
const primaryCTA=heroContent.querySelector('.btn-primary');if(primaryCTA){primaryCTA.textContent='Get Started Free';primaryCTA.href='assessment/index.html';}
const secondaryCTA=heroContent.querySelector('.btn-secondary');if(secondaryCTA){secondaryCTA.textContent='See Success Stories';secondaryCTA.href='#testimonials';}
const urgencyElement=document.createElement('div');urgencyElement.className='hero-urgency';urgencyElement.innerHTML='<p><i class="fas fa-clock"></i> Limited Time: Free AI Readiness Assessment ($499 value)</p>';urgencyElement.style.backgroundColor='rgba(251, 188, 5, 0.1)';urgencyElement.style.border='1px solid rgba(251, 188, 5, 0.3)';urgencyElement.style.borderRadius='4px';urgencyElement.style.padding='10px 15px';urgencyElement.style.marginTop='20px';urgencyElement.style.display='flex';urgencyElement.style.alignItems='center';urgencyElement.style.justifyContent='center';urgencyElement.querySelector('i').style.marginRight='8px';urgencyElement.querySelector('i').style.color='#fbbc05';heroContent.appendChild(urgencyElement);if(primaryCTA){primaryCTA.addEventListener('click',function(){trackEvent('hero_cta_click',{variant:'B',cta:'primary'});});}
if(secondaryCTA){secondaryCTA.addEventListener('click',function(){trackEvent('hero_cta_click',{variant:'B',cta:'secondary'});});}}
function trackEvent(eventName,eventParams){console.log(`[AB Test]Event:${eventName}`,eventParams);}
window.resetABTest=function(){localStorage.removeItem('hero_variant');window.location.reload();};