document.addEventListener('DOMContentLoaded',function(){console.log('Initializing terminal theme...');initMatrixBackgrounds();initAnimations();initTerminalInteractions();initTypingEffects();initGlitchElements();console.log('Terminal theme initialized successfully');});function initMatrixBackgrounds(){const matrixCanvases=document.querySelectorAll('.matrix-bg');matrixCanvases.forEach(canvas=>{if(canvas.tagName.toLowerCase()==='canvas'){const ctx=canvas.getContext('2d');const parent=canvas.parentElement;canvas.width=parent.offsetWidth;canvas.height=parent.offsetHeight;const characters='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ｦｧｨｩｪｫｬｭｮｯｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃ';const fontSize=14;const columns=Math.floor(canvas.width/fontSize);const drops=[];for(let i=0;i<columns;i++){drops[i]=Math.random()*-canvas.height;}
ctx.fillStyle='#00ff41';ctx.font=`${fontSize}px monospace`;function drawMatrix(){ctx.fillStyle='rgba(10, 10, 18, 0.05)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#00ff41';for(let i=0;i<columns;i++){const char=characters.charAt(Math.floor(Math.random()*characters.length));ctx.fillText(char,i*fontSize,drops[i]*fontSize);if(drops[i]*fontSize>canvas.height&&Math.random()>0.98){drops[i]=0;}
drops[i]++;}
requestAnimationFrame(drawMatrix);}
drawMatrix();}});}
function initAnimations(){const animatedElements=document.querySelectorAll('.animate-fade-in, .animate-fade-up');const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.style.opacity='';entry.target.style.transform='';observer.unobserve(entry.target);}});},{root:null,threshold:0.1,rootMargin:'0px 0px -50px 0px'});animatedElements.forEach(el=>{observer.observe(el);});}
function initTerminalInteractions(){const faqItems=document.querySelectorAll('.terminal-faq');faqItems.forEach(item=>{const question=item.querySelector('.terminal-faq-question');question.addEventListener('click',()=>{item.classList.toggle('open');});});const terminalButtons=document.querySelectorAll('.terminal-button');terminalButtons.forEach(button=>{button.addEventListener('click',(e)=>{e.stopPropagation();if(button.classList.contains('red')){const terminal=button.closest('.section-terminal');if(terminal){terminal.style.display='none';}}});});}
function initTypingEffects(){const typingElements=document.querySelectorAll('.typing-effect');typingElements.forEach(element=>{const text=element.getAttribute('data-text')||element.textContent;const speed=parseInt(element.getAttribute('data-speed')||50);element.textContent='';let i=0;function typeWriter(){if(i<text.length){element.textContent+=text.charAt(i);i++;setTimeout(typeWriter,speed);}else{element.classList.add('typing-complete');}}
typeWriter();});}
function initGlitchElements(){const glitchElements=document.querySelectorAll('.glitch');glitchElements.forEach(element=>{if(!element.hasAttribute('data-text')){element.setAttribute('data-text',element.textContent);}});}
window.addEventListener('resize',function(){initMatrixBackgrounds();});